spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url= jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=COLEGIO
spring.datasource.username=sa
spring.datasource.password=Panda1997
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServer2012Dialect

spring.jpa.hibernate.ddl-auto = none